export enum Types {
  INVESTMENT_EXPENSE = 'INVESTMENT_EXPENSE',
  CATTLE_SALE = 'CATTLE_SALE',
  BUY_CATTLE = 'BUY_CATTLE',
  MEDICINE = 'MEDICINE',
  PESTICIDE = 'PESTICIDE',
  FEED = 'FEED',
  STAFF = 'STAFF',
  INVESTMENT = 'INVESTMENT'
}
